CREATE TABLE mufaj(
      id          id,
      nev text,
      leiras text);

insert into mufaj (nev,leiras) values ('alternatív rock','Az alternatív rock a rockzene egyik műfaja, amely az 1980-as években jött létre és széles körben elterjedt az 1990-es években. Az alternatív rock számos alműfajból áll, melyek az 1980-as években a indie rockból vált ki. Az alternatív rock alműfajai a grunge, a Britpop, a gothic rock és az indie pop.');
insert into mufaj (nev,leiras) values ('blues','A blues egyszerre egy zenei forma és egy zenei műfaj, amely a 19. századi, Egyesült Államokbeli mélydéli afroamerikai közösségektől származik, spirituális- és munkadalokból, hollerekből, üvöltésekből, kántálásokból és ritmikus elbeszélő-balladákból áll. A blues alapját a tipikus akkordmenet és a blue note jellemzi.');
insert into mufaj (nev,leiras) values ('country','A countryzene az Amerikai Egyesült Államok déli részén élő, főleg skótok, írek zenéje, akik a saját népzenéjüket az Amerikában hallott blueszal keverték. A stílusnak ezen kívül gospel gyökerei is vannak. A country amerikai „farmerzene” vagy népzene, mely elsősorban a fehérek körében népszerű. Kezdetben a gyapotföldeken dolgozók zenéje volt, munkadalok formájában.');
insert into mufaj (nev,leiras) values ('dance','A dance (az angol dance „tánc” szóból) a modern, többnyire elektronikus eszközökkel – szintetizátorokkal vagy számítógéppel – előállított tánczenei műfajok gyűjtőneve. Jellemzői az elektronikus, gépies hangzás, a legkülönfélébb mesterséges, futurisztikus hangeffektusok, gyors – 145 BPM körüli – ritmus, illetve az alapütemet adó, jellegzetes elektronikus dobgép.');
insert into mufaj (nev,leiras) values ('disco','A diszkó (angolul: disco) tánczenei stílus. A műfaj a hetvenes évek második felében volt népszerűségének tetőpontján. Jellemzője az ütemes könnyűzene, melyet laza, vagy akár kombináltabb táncelemekkel kísérnek a műfaj kedvelői, továbbá azok feltűnő, divatos, vagy annak szánt ruházata, valamint a zenét és táncok kísérő színes fényeffektusok, ezekkel főleg a műfaj számára létrehozott diszkóklubokban lehetett találkozni. Ilyen külsőségek például a flitterek, a színes lámpák, vagy a fényt széttükröző diszkógömb.');
insert into mufaj (nev,leiras) values ('drum and bass','A Drum and Bass (DnB vagy Drum ''n Bass) egy dinamikus és ritmuscentrikus elektronikus zenei műfaj, amely két kulcsfontosságú elemre épül: a dobokra (drum) és a basszusokra (bass). A stílus a ''90-es évek elején fejlődött ki az Egyesült Királyságban, különféle zenei hatásokból merítve.');
insert into mufaj (nev,leiras) values ('drumstep','A Drumstep egy olyan zenei műfaj, amely a Drum and Bass és a Dubstep elemeit kombinálja. Mivel a Drumstep ötvözi a két műfajt, azonban kisebb tempóban játszódik (kb. 160-175 BPM), különféle kreatív lehetőségeket nyújt az elektronikus zenei producereknek.');
insert into mufaj (nev,leiras) values ('dubstep','A Dubstep egy elektronikus zenei műfaj, amely eredetileg az Egyesült Királyságban alakult ki a 2000-es évek elején. A stílust a mély basszusok, ritmikus ütemek és a karakteres hangzás jellemzi. Dubstepet gyakran használják klubokban és elektronikus zenei eseményeken, és hozzájárult a modern elektronikus zene sokszínűségéhez.');
insert into mufaj (nev,leiras) values ('elektronikus rock','Az elektronikus rock egy olyan zenei stílus, amely az elektronikus zene és a rockzene elemeit egyesíti. Ez a műfaj a hagyományos gitáralapú rockzenére, valamint az elektronikus zene különböző stílusaival kombinálja a szintetizátorokat, dobgépeket és más elektronikus hangszereket. Az elektronikus rocknak számos változata létezik, a könnyedebb és poposabb hangzásoktól a nehezebb és kísérletezőbb megközelítésekig.');
insert into mufaj (nev,leiras) values ('fusion jazz','A Fusion Jazz egy zenei stílus, amely a jazzt és más zenei műfajokat, például a rock, a funk, a blues vagy a latin, ötvözi. Ezt a műfajt a ''60-as évek végén és a ''70-es évek elején alakították ki, és az azóta eltelt évek során folyamatosan fejlődött. A Fusion Jazz egyfajta hídlépést jelent a jazz hagyományai és a különböző modern stílusok között.');
insert into mufaj (nev,leiras) values ('grunge','A Grunge egy zenei stílus és egyben az alternatív rock alcsoportja, amely az 1980-as évek végén és a 1990-es évek elején jött létre, főként az Egyesült Államok északnyugati részén, különösen Seattle-ben. A grunge zenei irányzat az underground punk és alternatív rock stílusokból merített, és hangsúlyozta a nyers, őszinte hangzást és a szövegekben rejlő érzelmi kifejeződést.');
insert into mufaj (nev,leiras) values ('hard rock','A Hard Rock egy erőteljes és hangos rockzenei műfaj, amely a 1960-as és 1970-es években fejlődött ki. Jellemző rá az erős ritmus, a hangsúlyos gitárszólók és az energiaitaltól duzzadó hangzásvilág. A Hard Rock gyakran ötvözi a blues és a rock''nroll elemeket, de erőteljesebb gitárhangzásra és keményebb ütemre helyezi a hangsúlyt.');
insert into mufaj (nev,leiras) values ('hiphop','A Hip-Hop egy zenei műfaj és kulturális mozgalom, amely az 1970-es években keletkezett afroamerikai és latin-amerikai közösségek New York-i negyedében. A Hip-Hop kifejezi a fiatalok kreativitását és azokat a társadalmi kihívásokat, amelyekkel szembesülnek. ');
insert into mufaj (nev,leiras) values ('house','A house zene egy elektronikus zenei műfaj, amelyet négy negyedes ritmus, illetve 120 és 130 BPM közötti tempó jellemez. A műfajt az 1980-as években hozták létre Chicago underground zenei kultúrájának DJ-jei, amikor a szubkultúrához tartozó DJ-k elkezdtek disco daloknak mechanikusabb lüktetést és mélyebb basszust adni.');
insert into mufaj (nev,leiras) values ('fusion','A fúziós zene olyan zenei műfaj, amely két vagy több stílus kombinációjaként jött létre. A rock and roll például eredetileg a blues, a gospel és a country zene fúziójaként fejlődött ki. '); 
insert into mufaj (nev,leiras) values ('klasszikus zene','A klasszikus zene egy időtálló zenei műfaj, amely kiterjed a barokktól a romantikus korszakig és a kortárs zeneig. Jellemzője a formális struktúrák, az összetett hangszerelés és a hangszeres vagy vokális szólamokban megnyilvánuló művészi kifejeződés. A klasszikus zene a világ kultúrájának gazdag örökségét képviseli, és a művészi mélység és emocionális sokszínűség terén kiemelkedő.');
insert into mufaj (nev,leiras) values ('nu-metal','A nu metal zenei irányzat az 1990-es évek közepén kialakult, a grunge és az alternatív metal zenei hagyományait a hiphoppal, az elektronikus zenével és más metalirányzatokkal ötvöző könnyűzenei műfaj.');
insert into mufaj (nev,leiras) values ('metal','A Metal egy erőteljes és agresszív zenei műfaj, melyet hangsúlyos gitárriffek, erős dobok és intenzív ének jellemzik. A különböző alcsoportok, mint a heavy metal, thrash metal vagy black metal, különböző hangzást és témákat képviselnek. A Metal gyakran kifejezi a lázadást, a sötétséget és az erőteljes hangzást a hallgatók számára.');
insert into mufaj (nev,leiras) values ('pop','A Pop egy könnyed, széles körben kedvelt zenei műfaj, melyet a könnyen emészthető dallamok, egyszerű struktúrák és szórakoztató stílusok jellemznek. A Pop zenére gyakran jellemző a díszes hangszerelés, az érzelmi dalszövegek és az általánosan pozitív hangulat. Ez a műfaj folyamatosan változik és alkalmazkodik a korszakok divatjaihoz, és a popzenei előadók rendszerint nagy hatást gyakorolnak a zeneiparra és a kulturális színtérre.');
insert into mufaj (nev,leiras) values ('k-pop','A K-pop vagy koreai popzene többek között elektronikus, hiphop, pop, rock és R&B alapokon nyugszik és különálló zenei műfajként tartják számon. A koreai popzene alapjai az 1920-as évek trot műfajára vezethetőek vissza, ezeket a dalokat a japán enkadalok befolyásolták. ');
insert into mufaj (nev,leiras) values ('progresszív rock','A Progresszív Rock egy kísérletező jellegű és művészi megközelítésű zenei műfaj, amely a 1960-as és 1970-es években alakult ki. Jellemzője az összetett hangszerelés, a hosszabb kompozíciók, az egyedi időaláírások és a kifinomult zenei struktúrák. A Progresszív Rock gyakran egyesíti a rockzenét a klasszikus, jazz, blues és más műfajokkal, miközben hangsúlyozza a zenészek virtuóz képességeit és a zenei kísérletezést.');
insert into mufaj (nev,leiras) values ('punk','A Punk egy energikus és lázadó zenei műfaj, amely a 1970-es években született az Egyesült Államokban és az Egyesült Királyságban. Jellemző rá az egyszerű akkordok, a rövid és gyors dalok, valamint az őszinte és társadalomkritikus szövegek. A Punk zene a függetlenséget, a lázadást és az ellenkultúrát fejezi ki, és olyan zenekarokkal hozható összefüggésbe, mint a Ramones, a Sex Pistols és a The Clash.');
insert into mufaj (nev,leiras) values ('rap','A Rap egy kifejező és ritmikus zenei műfaj, amely a szavakat és a rímeket hangsúlyozza, gyakran ütemes zenére. Jellemzője az éles szólamok, a szókincs gazdagsága és a ritmikus recitálás. A Rap eredetileg az afroamerikai közösségekből nőtt ki, de azóta globálisan elterjedt, és számos stílust és témát ölel fel, a társadalomkritikától az önfejezésig és az életkörülmények bemutatásáig.');
insert into mufaj (nev,leiras) values ('thrash metal','A thrash metal a heavy metal egyik alműfaja, amely az 1980-as évek elején-közepén alakult ki többé-kevésbé egymástól függetlenül az Egyesült Államokban, illetve Európában. Legegyszerűbb megközelítésben a hardcore punk és a heavy metal keveréke, de a műfaj nehezen kategorizálható.');
insert into mufaj (nev,leiras) values ('rhythm and blues (R&B)','A Rhythm and Blues (R&B) egy zenei műfaj, amely az afroamerikai közösségből ered, és a 1940-es évek végétől alakult ki. Jellemzője a blues, a jazz, a gospel és a rock and roll elemek keveredése. Az R&B hangsúlyozza az érzelmeket és a ritmusokat, és a dallamokon túl a hangsúly a szólamok kifejeződésén, a vokális tehetségen és a ritmikus elemeken van. Az R&B számos alcsoportra oszlik, beleértve a soul, a funk és az urban contemporary stílusokat, és hatással volt a pop- és a hip-hop zenére is.'); 
insert into mufaj (nev,leiras) values ('rock','A Rock egy sokszínű és dinamikus zenei műfaj, amely az 1950-es évek elején alakult ki, és azóta számos alcsoportra tagozódott. Jellemzője a gitáralapú hangszerelés, az erős ütemek, és az énekes központúság. A Rock zene számos stílust magában foglal, beleértve a classic rockot, az alternatív rockot, a punkot, a hard rockot, a soft rockot és még sok mást. Ez a műfaj gyakran kifejezi az érzelmeket, az önkifejezést, és a társadalmi üzeneteket, és nagy hatást gyakorolt a zenei tájképre és a kultúrára.');
insert into mufaj (nev,leiras) values ('latin','A Latin zene egy kifejező és sokszínű műfaj, amely Latin-Amerika kulturális hagyományaiból ered. Jellemző rá a ritmusok gazdagsága, az érzéki dallamok és a különböző stílusok, mint például a salsa, a merengue, a bachata, a cumbia, a reggaeton és mások. A Latin zene gyakran hangsúlyozza a táncolhatóságot és a pozitív életérzést, és az énekesek vagy zenekarok gyakran keverik a helyi hagyományokat más stílusokkal, létrehozva egyedi és élénk hangzásvilágot.');
insert into mufaj (nev,leiras) values ('techno','A Techno egy lendületes és elektronikus zenei műfaj, amely az 1980-as évek elején alakult ki. Jellemző rá az ismétlődő ütemek, a szintetizátorok dominanciája és az innovatív hangzásvilág. A Techno célja a táncolhatóság és az elektronikus hangzás kreatív kifejezése, és fontos szerepe van az elektronikus tánczenei kultúrában. A műfaj számos alműfajt ölel fel, beleértve a house, trance és techno subgenres-t is.');
insert into mufaj (nev,leiras) values ('trance','A Trance egy elektronikus zenei műfaj, amely az 1990-es évek elején alakult ki. Jellemzője az ismétlődő ritmusok, a hangsúlyos ütemek és az atmoszférikus hangzásvilág. A Trance célja a hallgatók mélyebb élménye és a zenébe való elmerülés. A műfaj gyakran tartalmaz hipnotikus és érzelmes elemeket, és különféle stílusokat ölel fel, beleértve az uplifting trance-t, a progressive trance-t és a psytrance-t is. A Trance széles körben népszerű a klubokban és az elektronikus zenei fesztiválokon.');
insert into mufaj (nev,leiras) values ('trap','A Trap egy olyan zenei stílus, amely a hip-hop és az elektronikus zene elemeket kombinálja. Jellemzője az alacsony basszusok, a hangsúlyos dobok és a specifikus ritmikus struktúrák. A Trap eredetileg a déli hip-hop környezetéből fejlődött ki, és később terjedt el az elektronikus zenei körökben is. A műfaj gyakran használ különböző hanghatásokat és hangszerelési technikákat, és a dallamokat a ritmusokon és a basszusokon keresztül hangsúlyozza. A Trap zenére gyakran jellemző az autotune használata és a szub-basszusok intenzív hangsúlya.');
insert into mufaj (nev,leiras) values ('electro swing','Az Electro swing vagy a swing house egy elektronikus tánczenei műfaj, amely a vintage vagy a modern swing és jazz elemeit ötvözi house-zal és hiphoppal.');
insert into mufaj (nev,leiras) values ('soul','A soul zene egy stílusos és érzelmes műfaj, amely a 20. század második felében fejlődött ki az afroamerikai közösségekből származó gospel, blues és rhythm and blues elemekből. A soul jellegzetes hangzását a kifinomult vokálok, erőteljes érzelmek, és gyakran a szívhez szóló szövegek alkotják. A stílusban hangsúlyos a szólamokban gazdag énekstílus, a ritmikus intenzitás és a hangsúlyos ritmusszekció.');
insert into mufaj (nev,leiras) values ('glam rock','A glam rock a rockzene egyik stílusa, amely a korai 70-es években, a poszt-hippi korszakban került az előtérbe. Javarészt angol együttesek által érte el a tetőpontját 1971 és 1973 között. A műfaj nagy hatással volt a japánokra, ahol visual kei néven saját zenei irányzat fejlődött ki.');
insert into mufaj (nev,leiras) values ('elektronikus','Az elektronikus zene egy olyan zenei műfaj, amely a zenei hangok generálásában, manipulálásában és szintetizálásában alkalmazza az elektronikus eszközöket és technológiákat. Ez a műfaj rendkívül változatos és széleskörű, több alfajt tartalmaz, amelyek eltérő hangzásokat és stílusokat képviselnek. ');
insert into mufaj (nev,leiras) values ('folk','A folk-rock egy a népzene és a rockzene keveredésével létrejött zenei műfaj, mely az 1960-as évek közepén jelent meg az Amerikai Egyesült Államokban és Egyesült Királyságban.');
insert into mufaj (nev,leiras) values ('reggae','A reggae egy könnyűzenei műfaj, amely az 1960-as években fejlődött ki Jamaicában. A reggae megnevezést tágabb értelemben szokták használni az összes jamaicai zenére, beleértve a ska, rocksteady, dub, dancehall és ragga műfajokat is.');
insert into mufaj (nev,leiras) values ('indie pop','Az indie pop egy alternatív könnyűzenei műfaj, amely az Egyesült Királyságban jött létre az 1980-as évek derekán.');
insert into mufaj (nev,leiras) values ('pop rock','A pop-rock olyan zenei stílus, amely egyesíti magában a rock és popzene elemeit. A dalokat fülbemászó dallamok, egyszerű dalszerkezet, valamint fokozott gitárhasználat, karakteres ritmusszekció és némileg agresszív hozzáállás jellemzi.');
insert into mufaj (nev,leiras) values ('industrial metal','Az industrial metal, azaz ipari metal a heavy metalnak az indusztriális zene hatásával létrejött alműfaja. Zeneiségét a sokszor szigorú, gépies gitárriffek és az elektronika széles körű használata jellemzik.');
insert into mufaj (nev,leiras) values ('heavy metal','A heavy metal rockzenei műfaj, amely 1968 és 1974 között jött létre. A heavy metalt életre hívó, blues-rock- és pszichedelikusrock-gyökerekkel rendelkező együttesek gitár- és dobközpontú, vastag, kemény hangzást alakítottak ki, melyet erős torzítás és gyors gitárszólók jellemeznek. ');
insert into mufaj (nev,leiras) values ('kelta','A kifejezés egy széles körű zeneműfajra utal, amelyet Írország, Skócia, Wales, Bretagne (Franciaországban) és más kelta régiók kultúráihoz kapcsolnak. A kelta zene számos stílusban és befolyásban gazdag, évszázadokon át alakult ki, hagyományos és kortárs elemeket egyaránt magában foglalva. ');
insert into mufaj (nev,leiras) values ('indie rock','Az "indie rock" rövidítése az "independent rock" kifejezésből származik, és egy olyan zenei műfajt jelöl, amely hangsúlyozza a függetlenséget a nagy kiadóktól és a mainstream zenei ipartól. Az indie rock gyakran összekapcsolódik a független lemezkiadókkal, kisebb koncerttermekkel, és általában magasabb fokú kreatív kontrollt biztosít az előadóknak.');
insert into mufaj (nev,leiras) values ('pszichedelikus rock','A pszichedelikus rock olyan zenei stílus, melyet a drogok – cannabis, pszilocibin, meszkalin és különösen az LSD – tudatmódosító hatása inspirál, és a módosult tudatállapot hangulatát igyekszik visszaadni. A pszichedelikus zenének több más típusa van, mely ugyanonnan ered, de később eltért a divatos rockzenétől. ');
insert into mufaj (nev,leiras) values ('post-hardcore','A post-hardcore a hardcore punk zene olyan alműfaja, ami összetettebb hangzást alkalmaz. A műfaj megteremtő zenekarainak tartották a Fugazit, Big Blacket és a Jawboxot. ');