-- location1
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l1_center_1','Center 1','allo',1.5,3000,null,'l1');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l1_center_2','Center 2','allo',1,3100,null,'l1');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l1_bal_szarny','Bal szárny','allo',1.4,800,null,'l1');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l1_jobb_szarny','Jobb szárny','allo',1.4,800,null,'l1');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l1_vip_jobb','Vip jobb','ulo',3.5,100,'VIP','l1');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l1_vip_bal','Vip bal','ulo',3.5,100,'VIP','l1');
-- location1

-- location2
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l2_center_1','Center 1','allo',1.5,2500,null,'l2'); 
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l2_center_2','Center 2','allo',1,1500,null,'l2');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l2_center_3','Center 3','allo',1,1500,null,'l2');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l2_bal_szarny_1','Bal szárny 1','allo',1.3,500,null,'l2');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l2_bal_szarny_2','Bal szárny 2','allo',1.4,800,null,'l2');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l2_jobb_szarny_1','Jobb szárny 1','allo',1.3,500,null,'l2');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l2_jobb_szarny_2','Jobb szárny 2','allo',1.4,800,null,'l2');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l2_vip_jobb','Vip jobb','ulo',3.5,100,'VIP','l2');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l2_vip_bal','Vip bal','ulo',3.5,100,'VIP','l2');
-- location2

-- location3
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_also_a','A-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_also_b','A-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_also_c','A-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_also_d','A-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_also_e','A-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_also_f','A-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_also_g','A-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_also_h','A-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_felso_i','A-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_felso_j','A-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_felso_k','A-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_a_felso_l','A-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_also_a','B-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_also_b','B-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_also_c','B-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_also_d','B-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_also_e','B-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_also_f','B-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_also_g','B-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_also_h','B-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_felso_i','B-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_felso_j','B-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_felso_k','B-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_b_felso_l','B-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_also_a','C-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_also_b','C-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_also_c','C-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_also_d','C-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_also_e','C-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_also_f','C-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_also_g','C-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_also_h','C-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_felso_i','C-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_felso_j','C-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_felso_k','C-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_c_felso_l','C-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_also_a','D-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_also_b','D-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_also_c','D-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_also_d','D-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_also_e','D-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_also_f','D-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_also_g','D-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_also_h','D-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_felso_i','D-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_felso_j','D-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_felso_k','D-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_d_felso_l','D-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_also_a','E-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_also_b','E-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_also_c','E-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_also_d','E-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_also_e','E-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_also_f','E-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_also_g','E-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_also_h','E-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_felso_i','E-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_felso_j','E-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_felso_k','E-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_e_felso_l','E-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_also_a','F-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_also_b','F-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_also_c','F-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_also_d','F-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_also_e','F-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_also_f','F-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_also_g','F-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_also_h','F-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_felso_i','F-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_felso_j','F-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_felso_k','F-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_f_felso_l','F-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_also_a','G-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_also_b','G-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_also_c','G-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_also_d','G-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_also_e','G-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_also_f','G-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_also_g','G-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_also_h','G-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_felso_i','G-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_felso_j','G-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_felso_k','G-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_g_felso_l','G-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_also_a','H-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_also_b','H-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_also_c','H-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_also_d','H-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_also_e','H-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_also_f','H-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_also_g','H-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_also_h','H-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_felso_i','H-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_felso_j','H-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_felso_k','H-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_h_felso_l','H-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_also_a','I-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_also_b','I-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_also_c','I-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_also_d','I-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_also_e','I-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_also_f','I-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_also_g','I-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_also_h','I-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_felso_i','I-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_felso_j','I-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_felso_k','I-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_i_felso_l','I-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_also_a','J-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_also_b','J-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_also_c','J-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_also_d','J-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_also_e','J-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_also_f','J-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_also_g','J-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_also_h','J-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_felso_i','J-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_felso_j','J-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_felso_k','J-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_j_felso_l','J-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_also_a','K-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_also_b','K-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_also_c','K-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_also_d','K-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_also_e','K-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_also_f','K-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_also_g','K-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_also_h','K-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_felso_i','K-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_felso_j','K-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_felso_k','K-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_k_felso_l','K-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_also_a','L-alsó','ulo',2.1,50,'A','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_also_b','L-alsó','ulo',2.0,52,'B','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_also_c','L-alsó','ulo',1.9,54,'C','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_also_d','L-alsó','ulo',1.8,56,'D','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_also_e','L-alsó','ulo',1.7,58,'E','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_also_f','L-alsó','ulo',1.6,60,'F','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_also_g','L-alsó','ulo',1.5,62,'G','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_also_h','L-alsó','ulo',1.4,64,'H','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_felso_i','L-felsõ','ulo',1.3,66,'I','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_felso_j','L-felsõ','ulo',1.2,68,'J','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_felso_k','L-felsõ','ulo',1.1,70,'K','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_l_felso_l','L-felsõ','ulo',1.0,72,'L','l3');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l3_center','Center','allo',2.2,4000,null,'l3');
-- location3

-- location4
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_a_a','A szektor','ulo',2.5,80,'A','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_a_b','A szektor','ulo',2.3,84,'B','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_a_c','A szektor','ulo',2.2,88,'C','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_a_d','A szektor','ulo',2.1,92,'D','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_a_e','A szektor','ulo',2.1,96,'E','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_b_f','B szektor','ulo',2.0,52,'F','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_b_g','B szektor','ulo',2.0,56,'G','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_b_h','B szektor','ulo',1.9,60,'H','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_b_i','B szektor','ulo',1.9,64,'I','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_b_j','B szektor','ulo',1.8,68,'J','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_b_k','B szektor','ulo',1.8,70,'K','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_c_f','C szektor','ulo',2.0,52,'F','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_c_g','C szektor','ulo',2.0,56,'G','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_c_h','C szektor','ulo',1.9,60,'H','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_c_i','C szektor','ulo',1.9,64,'I','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_c_j','C szektor','ulo',1.8,68,'J','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_c_k','C szektor','ulo',1.8,70,'K','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_d_l','D szektor','ulo',1.6,92,'L','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_d_m','D szektor','ulo',1.6,96,'M','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_d_n','D szektor','ulo',1.4,100,'N','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_d_o','D szektor','ulo',1.4,104,'O','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_d_p','D szektor','ulo',1.2,108,'P','l4');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l4_d_q','D szektor','ulo',1.0,112,'Q','l4');
-- location4

-- location5
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_a_a','A-szektor','ulo',2.1,40,'A','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_a_b','A-szektor','ulo',2.0,42,'B','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_a_c','A-szektor','ulo',1.9,44,'C','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_b_a','B-szektor','ulo',2.1,40,'A','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_b_b','B-szektor','ulo',2.0,42,'B','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_b_c','B-szektor','ulo',1.9,44,'C','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_c_d','C-szektor','ulo',1.7,50,'D','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_c_e','C-szektor','ulo',1.6,48,'E','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_c_f','C-szektor','ulo',1.5,46,'F','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_c_g','C-szektor','ulo',1.4,44,'G','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_d_d','D-szektor','ulo',1.7,50,'D','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_d_e','D-szektor','ulo',1.6,48,'E','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_d_f','D-szektor','ulo',1.5,46,'F','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_d_g','D-szektor','ulo',1.4,44,'G','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_e_h','E-szektor','ulo',1.4,50,'H','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_e_i','E-szektor','ulo',1.3,48,'I','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_e_j','E-szektor','ulo',1.2,46,'J','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_e_k','E-szektor','ulo',1.1,44,'K','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_f_h','F-szektor','ulo',1.4,50,'H','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_f_i','F-szektor','ulo',1.3,48,'I','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_f_j','F-szektor','ulo',1.2,46,'J','l5');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l5_f_k','F-szektor','ulo',1.1,44,'K','l5');
-- location5

-- location6
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_a_also_a','A-alsó','ulo',1.9,60,'A','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_a_also_b','A-alsó','ulo',1.75,62,'B','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_a_also_c','A-alsó','ulo',1.6,64,'C','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_a_also_d','A-alsó','ulo',1.45,66,'D','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_a_also_e','A-alsó','ulo',1.3,68,'E','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_a_felso_f','A-felsõ','ulo',1.15,70,'F','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_a_felso_g','A-felsõ','ulo',1.0,72,'G','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_b_also_a','B-alsó','ulo',1.9,60,'A','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_b_also_b','B-alsó','ulo',1.75,62,'B','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_b_also_c','B-alsó','ulo',1.6,64,'C','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_b_also_d','B-alsó','ulo',1.45,66,'D','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_b_also_e','B-alsó','ulo',1.3,68,'E','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_b_felso_f','B-felsõ','ulo',1.15,70,'F','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_b_felso_g','B-felsõ','ulo',1.0,72,'G','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_c_also_a','C-alsó','ulo',2.2,60,'A','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_c_also_b','C-alsó','ulo',2.05,62,'B','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_c_also_c','C-alsó','ulo',1.9,64,'C','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_c_also_d','C-alsó','ulo',1.75,66,'D','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_c_also_e','C-alsó','ulo',1.6,68,'E','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_c_felso_f','C-felsõ','ulo',1.45,70,'F','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_c_felso_g','C-felsõ','ulo',1.3,72,'G','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_d_also_a','D-alsó','ulo',2.2,60,'A','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_d_also_b','D-alsó','ulo',2.05,62,'B','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_d_also_c','D-alsó','ulo',1.9,64,'C','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_d_also_d','D-alsó','ulo',1.75,66,'D','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_d_also_e','D-alsó','ulo',1.6,68,'E','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_d_felso_f','D-felsõ','ulo',1.45,70,'F','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_d_felso_g','D-felsõ','ulo',1.3,72,'G','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_e_also_a','E-alsó','ulo',1.9,60,'A','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_e_also_b','E-alsó','ulo',1.75,62,'B','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_e_also_c','E-alsó','ulo',1.6,64,'C','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_e_also_d','E-alsó','ulo',1.45,66,'D','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_e_also_e','E-alsó','ulo',1.3,68,'E','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_e_felso_f','E-felsõ','ulo',1.15,70,'F','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_e_felso_g','E-felsõ','ulo',1.0,72,'G','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_f_also_a','F-alsó','ulo',1.9,60,'A','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_f_also_b','F-alsó','ulo',1.75,62,'B','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_f_also_c','F-alsó','ulo',1.6,64,'C','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_f_also_d','F-alsó','ulo',1.45,66,'D','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_f_also_e','F-alsó','ulo',1.3,68,'E','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_f_felso_f','F-felsõ','ulo',1.15,70,'F','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_f_felso_g','F-felsõ','ulo',1.0,72,'G','l6');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l6_center','Center','allo',2.4,2000,null,'l6');
-- location6

-- location7
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_center','A-center','allo','1.95',2600,null,'l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_1_a','A-alsó 1','ulo',1.96,60,'A','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_2_a','A-alsó 2','ulo',1.96,60,'A','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_1_b','A-alsó 1','ulo',1.84,60,'B','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_2_b','A-alsó 2','ulo',1.84,60,'B','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_1_c','A-alsó 1','ulo',1.72,60,'C','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_2_c','A-alsó 2','ulo',1.72,60,'C','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_1_d','A-alsó 1','ulo',1.6,60,'D','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_2_d','A-alsó 2','ulo',1.6,60,'D','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_1_e','A-alsó 1','ulo',1.48,60,'E','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_2_e','A-alsó 2','ulo',1.48,60,'E','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_1_f','A-alsó 1','ulo',1.36,60,'F','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_also_2_f','A-alsó 2','ulo',1.36,60,'F','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_felso_g','A-felsõ','ulo',1.24,120,'G','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_felso_h','A-felsõ','ulo',1.12,120,'H','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_a_felso_i','A-felsõ','ulo',1.0,120,'I','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_center','B-center','allo','1.95',2600,null,'l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_1_a','B-alsó 1','ulo',1.96,60,'A','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_2_a','B-alsó 2','ulo',1.96,60,'A','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_3_a','B-alsó 3','ulo',1.96,120,'A','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_1_b','B-alsó 1','ulo',1.84,60,'B','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_2_b','B-alsó 2','ulo',1.84,62,'B','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_3_b','B-alsó 3','ulo',1.84,122,'B','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_1_c','B-alsó 1','ulo',1.72,60,'C','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_2_c','B-alsó 2','ulo',1.72,64,'C','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_3_c','B-alsó 3','ulo',1.72,124,'C','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_1_d','B-alsó 1','ulo',1.6,60,'D','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_2_d','B-alsó 2','ulo',1.6,66,'D','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_3_d','B-alsó 3','ulo',1.6,126,'D','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_1_e','B-alsó 1','ulo',1.48,60,'E','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_2_e','B-alsó 2','ulo',1.48,68,'E','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_3_e','B-alsó 3','ulo',1.48,128,'E','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_1_f','B-alsó 1','ulo',1.36,60,'F','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_2_f','B-alsó 2','ulo',1.36,70,'F','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_also_3_f','B-alsó 3','ulo',1.36,130,'F','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_felso_1_g','B-felsõ-1','ulo',1.24,130,'G','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_felso_2_g','B-felsõ-2','ulo',1.24,130,'G','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_felso_1_h','B-felsõ-1','ulo',1.12,130,'H','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_felso_2_h','B-felsõ-2','ulo',1.12,130,'H','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_felso_1_i','B-felsõ-1','ulo',1.0,130,'I','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_b_felso_2_i','B-felsõ-2','ulo',1.0,130,'I','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_center','C-center','allo','1.95',2600,null,'l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_1_a','C-alsó 1','ulo',1.96,60,'A','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_2_a','C-alsó 2','ulo',1.96,60,'A','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_3_a','C-alsó 3','ulo',1.96,120,'A','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_1_b','C-alsó 1','ulo',1.84,60,'B','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_2_b','C-alsó 2','ulo',1.84,62,'B','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_3_b','C-alsó 3','ulo',1.84,122,'B','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_1_c','C-alsó 1','ulo',1.72,60,'C','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_2_c','C-alsó 2','ulo',1.72,64,'C','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_3_c','C-alsó 3','ulo',1.72,124,'C','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_1_d','C-alsó 1','ulo',1.6,60,'D','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_2_d','C-alsó 2','ulo',1.6,66,'D','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_3_d','C-alsó 3','ulo',1.6,126,'D','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_1_e','C-alsó 1','ulo',1.48,60,'E','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_2_e','C-alsó 2','ulo',1.48,68,'E','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_3_e','C-alsó 3','ulo',1.48,128,'E','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_1_f','C-alsó 1','ulo',1.36,60,'F','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_2_f','C-alsó 2','ulo',1.36,70,'F','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_also_3_f','C-alsó 3','ulo',1.36,130,'F','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_felso_1_g','C-felsõ-1','ulo',1.24,130,'G','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_felso_2_g','C-felsõ-2','ulo',1.24,130,'G','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_felso_1_h','C-felsõ-1','ulo',1.12,130,'H','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_felso_2_h','C-felsõ-2','ulo',1.12,130,'H','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_felso_1_i','C-felsõ-1','ulo',1.0,130,'I','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_c_felso_2_i','C-felsõ-2','ulo',1.0,130,'I','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_center','D-center','allo','1.95',2600,null,'l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_1_a','D-alsó 1','ulo',1.96,60,'A','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_2_a','D-alsó 2','ulo',1.96,60,'A','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_1_b','D-alsó 1','ulo',1.84,60,'B','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_2_b','D-alsó 2','ulo',1.84,60,'B','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_1_c','D-alsó 1','ulo',1.72,60,'C','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_2_c','D-alsó 2','ulo',1.72,60,'C','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_1_d','D-alsó 1','ulo',1.6,60,'D','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_2_d','D-alsó 2','ulo',1.6,60,'D','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_1_e','D-alsó 1','ulo',1.48,60,'E','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_2_e','D-alsó 2','ulo',1.48,60,'E','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_1_f','D-alsó 1','ulo',1.36,60,'F','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_also_2_f','D-alsó 2','ulo',1.36,60,'F','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_felso_g','D-felsõ','ulo',1.24,120,'G','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_felso_h','D-felsõ','ulo',1.12,120,'H','l7');
insert into szektor (szektor_id,szektor_nev,szektor_tipus,arszorzo,max_kapacitas,sorjelzes,helyszin_id) values ('l7_d_felso_i','D-felsõ','ulo',1.0,120,'I','l7');

-- location7